### ISSUE TITLE
Any chance an online station could adapt this for profanity detection 

### ISSUE THREAD

**Issue by redimongo** [stevenryoung/RadioDelay#10]
Hi like your code as it delays the audio from one source. But is there away that say when a producer press F5 that the incoming audio mutes and drops out the 10 seconds from incoming source and replaces it with a 10 second audio clip instead.

The goal is we need a 10 second profanity detection for an online station. 

Am happy to test and help write the additional code.  We need an open source solution as we are just starting up.

**Comment by stevenryoung** [comment]
This code could likely be adapted to that purpose fairly easily. You would need to add some code to listed for that keypress, and then add some code that overwrites the 10 second window you want to replace (likely the 5 seconds before you pressed the button and 5 seconds after in order to capture what was said and what will be said until you could disconnect a caller, etc.). Just FYI, your idea isn't exactly what modern radio stations do. They would take the current buffer (maybe 10-30 seconds), dump some portion of that (or maybe all of it). Then they would stretch the samples (making everyone appear to have a slightly deeper voice), until they built up the buffer to full size again. They do this to avoid dead air (or having to play some audio unrelated to the current conversation) as to keep the audiences interest. This code could be a good starting point for that also, but would require more modification. But yes, feel free to use/modify this code however you would like to (under the terms of the GPLv3 license), but I will not be able to help/advise further due to other commitments.
